# Series

In [1]:
import pandas as pd
import numpy as np

In [3]:
array_1 = np.arange(2,7)
array_1

array([2, 3, 4, 5, 6])

In [5]:
array_1.dtype

dtype('int64')

In [4]:
series_1 = pd.Series(array_1)
series_1

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [13]:
series_1 = pd.Series(array_1,dtype='int8',index=['a','b','c','d','e'])
series_1

a    2
b    3
c    4
d    5
e    6
dtype: int8

In [12]:
a_series = pd.Series('a',dtype='object')
a_series

0    a
dtype: object

In [9]:
a_str = 'a'
a_str

'a'

In [10]:
a_str + a_series

0    aa
dtype: object

In [15]:
dict_1 = {
    'a':2,
    'b':3,
    'c':4,
    'd':5,
    'e':6
}

In [17]:
series_1_dict = pd.Series(dict_1)
series_1_dict

a    2
b    3
c    4
d    5
e    6
dtype: int64

In [18]:
series_2 = pd.Series(2,dtype='int8',index=['a','b','c','d','e'])
series_2

a    2
b    2
c    2
d    2
e    2
dtype: int8

In [20]:
array_1[1]

np.int64(3)

In [22]:
series_1_dict.iloc[1]

np.int64(3)

In [23]:
array_1[2:]

array([4, 5, 6])

In [24]:
series_1_dict.iloc[2:]

c    4
d    5
e    6
dtype: int64

In [25]:
array_1[[1,3]]

array([3, 5])

In [26]:
series_1_dict.iloc[[1,3]]

b    3
d    5
dtype: int64

In [27]:
series_1_dict.to_numpy()

array([2, 3, 4, 5, 6])

In [29]:
series_1_dict

a    2
b    3
c    4
d    5
e    6
dtype: int64

In [31]:
'b' in series_1_dict

True

In [35]:
get_value = series_1_dict.get('z')

In [36]:
get_value == None

True

In [37]:
series_1_dict + series_1_dict

a     4
b     6
c     8
d    10
e    12
dtype: int64

In [38]:
series_1_dict * 3

a     6
b     9
c    12
d    15
e    18
dtype: int64

In [40]:
series_1 = pd.Series(array_1,dtype='int8',index=['a','b','c','d','e'],name='random outputs')
series_1

a    2
b    3
c    4
d    5
e    6
Name: random outputs, dtype: int8

In [41]:
series_1.name

'random outputs'

In [42]:
dict_2 = {
    'one':[1,2,3,4,5],
    'two':[3,4,5,6,7]
}
dict_2

{'one': [1, 2, 3, 4, 5], 'two': [3, 4, 5, 6, 7]}

In [44]:
df_2 = pd.DataFrame(dict_2)
df_2

one  two
0    1    3
1    2    4
2    3    5
3    4    6
4    5    7

In [56]:
list_2 = [
    {
        'a':1,
        'b':2,
        'd':'three'
    },
    {
        'a':4,
        'b':7,
        'c':9
    }
]

list_2

[{'a': 1, 'b': 2, 'd': 'three'}, {'a': 4, 'b': 7, 'c': 9}]

In [57]:
df_2 = pd.DataFrame(list_2, index=['first_row','second_row'])
df_2

a  b      d    c
first_row   1  2  three  NaN
second_row  4  7    NaN  9.0

In [60]:
df_2

a  b      d    c   e
first_row   1  2  three  NaN   3
second_row  4  7    NaN  9.0  11

In [61]:
df_2.loc['first_row']

a        1
b        2
d    three
c      NaN
e        3
Name: first_row, dtype: object

In [62]:
df_2.iloc[0]

a        1
b        2
d    three
c      NaN
e        3
Name: first_row, dtype: object

In [50]:
df_2['c']

first_row     NaN
second_row    9.0
Name: c, dtype: float64

In [58]:
for col in df_2.columns:
    print(2*'-->')
    print(col)
    print(df_2[col].dtype)

-->-->
a
int64
-->-->
b
int64
-->-->
d
object
-->-->
c
float64


In [59]:
df_2['e']=df_2['a']+df_2['b']
df_2

a  b      d    c   e
first_row   1  2  three  NaN   3
second_row  4  7    NaN  9.0  11

In [64]:
df_2[0:2]

a  b      d    c   e
first_row   1  2  three  NaN   3
second_row  4  7    NaN  9.0  11